name: cocktelia
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  provider: ^6.1.1
  get_it: ^7.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  assets:
    - assets/image/OIG2.NoyM0JZu50IYU.jpg
    - lib/widgets/category_card/data/json_category_card.json
    - lib/widgets/recipe_card/data/json_recipe_card.json
    - lib/recipe/data/json_recipe.json
  uses-material-design: true

  fonts:
  - family: Michroma-Regular
    fonts:
      - asset: assets/fonts/Michroma-Regular.ttf

  - family: SairaExtraCondensed-Regular
    fonts:
      - asset: assets/fonts/SairaExtraCondensed-Regular.ttf
